---
- name: Add path script
  become: true
  ansible.builtin.template:
    src: etc/tmp/kubes.sh.j2
    dest: /tmp/kubes.sh
    backup: true
    mode: 0644
    owner: root
    group: root
  tags:
    - kubes
    - M1038

- name: Install Kubes
  become: true
  ansible.builtin.command:
    cmd: sh /tmp/kubes.sh
...