---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      focal:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      jammy:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      kinetic:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      lunar:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: focal
    box: "bento/ubuntu-20.04"
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: jammy
    box: "ubuntu/jammy64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: kinetic
    box: "ubuntu/kinetic64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: lunar
    box: "lunar/20221227"
    box_url: "https://cloud-images.ubuntu.com/lunar/20221227/lunar-server-cloudimg-amd64-vagrant.box"
    box_download_checksum: "5576b35423437b60ddcbf2500a2700a5354947a080d83efc057f75d4a0e08789"
    box_download_checksum_type: "sha256"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
scenario:
  name: ubuntu
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
